# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K-t6IuQce3enNuNjLFx-1qbbR5kfmiSQ
"""

from google.colab import files
import pandas as pd



uploaded = files.upload()

data_adilla = pd.read_csv('/content/titanic.csv')
print(data_adilla)

data1 = data_adilla.loc[:,['Age','Pclass','Survived']]
print(data1)

#memvisualisasikan data titanic
data2 = data_adilla[['Age', 'Pclass', 'Survived']]
data2.plot(title='Persebaran Data', x='Age', y='Pclass', kind='scatter', c='Survived', colormap='Paired')

#memanipulasi data jumlah penumpang berdasarkan group Pclass
data3 = data_adilla[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
penumpang=data3.groupby('Pclass')['Name'].nunique()
print('Jumlah Penumpang:\n', penumpang)

#memfilter data penumpang yang selamat berdasarkan pclass
data4 = data_adilla[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
notsurvivedpassanger=data4['Pclass'].loc[data_adilla['Survived']==0]
print('Penumpang yang tidak survived:\n', notsurvivedpassanger.value_counts())
survivedpassanger=data4['Pclass'].loc[data_adilla['Survived']==1]
print('\nPenumpang yang survived:\n', survivedpassanger.value_counts())

data_prak = data_adilla[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
Kelamin=data_prak.groupby('Sex')['Name'].nunique()
print('Jumlah Kelamin:\n', Kelamin)

data_prak = data_adilla[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
notsurvivedpassanger=data_prak['Sex'].loc[data_adilla['Survived']==0]
print('Penumpang yang tidak survived:\n', notsurvivedpassanger.value_counts())
survivedpassanger=data_prak['Sex'].loc[data_adilla['Survived']==1]
print('\nPenumpang yang survived:\n', survivedpassanger.value_counts())